

lovelist0 = ["You have a face only a mother could love", "I can't imagine anyone would be particularly excited to marry you", "Good luck with that"]
healthlist0 = []
familylist0 = ["Sometimes your family purposely don't invite you to things.", "One of your family members is out to get you.", "You will want to hit your siblings, we definitley don't suggest this..."]
worklist0 = []
financelist0 = []
travellist0 = []

lovelist1 = []
healthlist1 = []
familylist1 = ["Call your family - they won't answer but it's worth a shot.", "The ghost that haunts your family home is angry with you.","You will get a gut feeling that one of your family members is ugly."]
worklist1 = []
financelist1 = []
travellist1 = [] 

lovelist2 = []
healthlist2 = []
familylist2 = ["You were a surprsie to your parents.", "Family rivalry is rife - control your ever present anger, they aren't worth it.", "Your competitive side will cause serious issues at game night."]
worklist2 = []
financelist2 = []
travellist2 = [] 

lovelist3 = []
healthlist3 = []
familylist3 = ["Someone in your family will be possessed by an evil spirit - my bet is it's you.", "You will betray your family - they deserved it.", "Your family think you don't have a backbone - continue proving them right."]
worklist3 = []
financelist3 = []
travellist3 = []

lovelist4 = []
healthlist4 = []
familylist4 = ["You will discover that you are the secret evil twin.", "Family drama is on the horizon - they know what you did.", "Minor tensions will arise today - will you remember to use your words?"]
worklist4 = []
financelist4 = []
travellist4 = [] 

lovelist5 = []
healthlist5 = []
familylist5 = ["An estranged uncle will tell you the truth about your birth.", "Be nice to your family - it is will writing season.", "Your future mother in law will not like you."]
worklist5 = []
financelist5 = []
travellist5 = [] 

lovelist6 = []
healthlist6 = []
familylist6 = ["You are not your pets favourite human - give them more treats.", "At family weddings this year you will be a liability.", "Your inheritance will come into question this week - tread carefully."]
worklist6 = []
financelist6 = []
travellist6 = []

lovelist7 = []
healthlist7 = []
familylist7 = ["One of your family members will eat your leftovers.", "Be wary of siblings, they will betray you to save themselves.", "Harm will come to you if you don't embarrass your children."]
worklist7 = []
financelist7 = []
travellist7 = [] 

lovelist8 = []
healthlist8 = []
familylist8 = ["Be wary of dinner invitations from family - they are not as innocent as they seem.", "Tension is brewing - your family may not agree with your choices this week.", "Someone in your family was swapped at birth."]
worklist8 = []
financelist8 = []
travellist8 = [] 

lovelist9 = []
healthlist9 = []
familylist9 = ["Take some time away from family this week - they are sick of you.", "A distant member of your family will turn up to insult you.", "You will have a gut feeling that your family went on holiday without you - they did."]
worklist9 = []
financelist9 = []
travellist9 = []

lovelist10 = []
healthlist10 = []
familylist10 = ["Your family have joined a cult - they will try to indoctrinate you.", "A distant member of your family will contact you about you car's extended warranty.", "You may find yourself cleaning crayon off the walls wondering where you went wrong."]
worklist10 = []
financelist10 = []
travellist10 = [] 

lovelist11 = []
healthlist11 = []
familylist11 = ["A distant member of your family has found your secret stash.", "You may find yourself alone at the dinner table, wondering where you went wrong.", "If you're going on a family holiday this summer, prepare for some drama."]
worklist11 = []
financelist11 = []
travellist11 = [] 
