lovelist0 = ["You have a face only a mother could love", "I can't imagine anyone would be particularly excited to marry you", "Good luck with that"]
healthlist0 = []
familylist0 = ["Sometimes your family purposely don't invite you to things.", "One of your family members is out to get you.", "You will want to hit your siblings, we definitley don't suggest this..."]
worklist0 = []
financelist0 = []
travellist0 = ["You are going to get sunburnt, use sun cream - or don't, I can't tell you what to do.", "Watch out for pickpockets, they target hopeless tourists like you.", "Watch out for exotic foods, food poisoning is in your future. Enjoy."]

lovelist1 = ["The situationship you are in is a relationship. Just pick up the courage to accept that, so you both can move forward.", "Asking someone out is daunting. You don't have it in you. Maybe work on that this week.", "You will see a beautiful stranger in the queue at the club. You will not be allowed in though."]
healthlist1 = []
familylist1 = ["Call your family - they won't answer but it's worth a shot.", "The ghost that haunts your family home is angry with you.","You will get a gut feeling that one of your family members is ugly."]
worklist1 = []
financelist1 = []
travellist1 = ["The airline you trust most will lose your luggage.", "I see a foreign romance in you future, it doesn't involve you but you will witness someone else's happiness.", "Stay at home, you are not suited to travel abroad."] 

lovelist2 = ["You already know what I'm going to say. Come back next week, maybe there will be some good news.", "The club isn't the best place to find a lover so you should try your housemate. That will end well.", "In a strange turn of events, you're fiery personality may actually be the reason you are in your current realtionship."]
healthlist2 = []
familylist2 = ["You were a surprsie to your parents.", "Family rivalry is rife - control your ever present anger, they aren't worth it.", "Your competitive side will cause serious issues at game night."]
worklist2 = []
financelist2 = []
travellist2 = ["Imagine beautiful beaches and cocktails. Hold onto that thought because its going to be a long while before you experience it again.", "You will be stuck on a day trip with the most annoying British family - its your family.", "Your seat partner on the plane will steal you armrest - stand your ground!"] 

lovelist3 = ["Ironically, the club IS the best place to find a lover. You're just never there.", "I see children in your future - they may be yours otherwise future you is spending an unreasonable amount time at the park.", "Someone loves you. It is your pet."]
healthlist3 = []
familylist3 = ["Someone in your family will be possessed by an evil spirit - my bet is it's you.", "You will betray your family - they deserved it.", "Your family think you don't have a backbone - continue proving them right."]
worklist3 = []
financelist3 = []
travellist3 = ["Try your best to not be British on holiday - other countries will not appreciate your sarcasm.", "Loud Americans will sit next to you on the plane - take your headphones!", "Sometimes booking the cheapest flights/hotels is not the best idea - keep this in mind."]

lovelist4 = ["You will meet a good looking barista. They will serve you coffee. Then they will tell you for the third time that they have a partner and that you are being creepy.", "Is that marriage I see on the horizon? Nope, that's a smudge on my window.", "You will regret not saying "hi" to the cutie in your seminar - you would have embarrassed yourself but at least you would have shot your shot."]
healthlist4 = []
familylist4 = ["You will discover that you are the secret evil twin.", "Family drama is on the horizon - they know what you did.", "Minor tensions will arise today - will you remember to use your words?"]
worklist4 = []
financelist4 = []
travellist4 = ["Unforutnately, there is no travelling in your near future - travelling costs money and currently you're broke.", "The German tourists will take all the sunbeads at the hotel pool.", "There will be no cold water at the hotel - you will need to come up with an ingenious way to cool down or just be uncomfortable and complain about it."] 

lovelist5 = ["Shoot your shot with that hottie you've been crushing on. Your hopes will most likely be crushed but that shouldn't stop you from trying.", "When the time comes for marriage and kids you will have lived many lives already.", "Summer romance is good while it lasts - unfortunately for you, it won't last."]
healthlist5 = []
familylist5 = ["An estranged uncle will tell you the truth about your birth.", "Be nice to your family - it is will writing season.", "Your future mother in law will not like you."]
worklist5 = []
financelist5 = []
travellist5 = ["You will suffer from lots of mosquito bites this summer - coat yourself in bug spray if you want to avoid the itching.", "There will be a time when you can afford to travel, that time is not now.", "That friend you made on holiday when you were 7 has forgotten about you."] 

lovelist6 = ["Summer romances never last. Winter romances on the other hand... will also not last for you.", "Sometimes its just easier not to say anything...", "Someone has got their eye on you. They may be a stalker but I can't quite tell."]
healthlist6 = []
familylist6 = ["You are not your pets favourite human - give them more treats.", "At family weddings this year you will be a liability.", "Your inheritance will come into question this week - tread carefully."]
worklist6 = []
financelist6 = []
travellist6 = ["You will win an all inclusive trip to Malta! Just kidding you won't.", "I have a feeling you will start to get travel sick, not just on boats but planes and cars too. Maybe even trains.", "Your tan lines will be embarrassing no matter what you do to try and fix them."]

lovelist7 = ["Your true love is just around the corner at Greggs. It's sausage rolls!", "You will meet someone this week that has only green flags. They ARE too good to be true.", "A little bit of booze will advance a budding relationship. I said a little bit."]
healthlist7 = []
familylist7 = ["One of your family members will eat your leftovers.", "Be wary of siblings, they will betray you to save themselves.", "Harm will come to you if you don't embarrass your children."]
worklist7 = []
financelist7 = []
travellist7 = ["A seagull will poop on you at the beach.", "You will burn your feet on the hot white sand - the salty water will not be pleasant after this.", "Your expensive foreign ice cream will fall on the floor."] 

lovelist8 = ["There is a spring in your step this week. Either you found a new sweetheart or you found spiders living in your underwear drawer.", "Sometimes you have to lower your standards else you will end up alone. Basically, go for people at your level.", "Trust your gut. It was right about the petrol station sushi and it knows what you need to do about you relationship situation."]
healthlist8 = []
familylist8 = ["Be wary of dinner invitations from family - they are not as innocent as they seem.", "Tension is brewing - your family may not agree with your choices this week.", "Someone in your family was swapped at birth."]
worklist8 = []
financelist8 = []
travellist8 = ["Knock off purchases rarely last very long - maybe leave the Gukki handbag next time.", "All the sunbeds at the beach will be taken if you get there after 10am - you will need to work on your morning routine if you want one.", "Your family will get annoyed with you for working while you are on holiday."] 

lovelist9 = ["There is romance in your future. You may have to go on dates with yourself to experience it though.", "Stop wating around for something to happen to you. Get out there, talk to people - they don't (always) bite.", "You could be quite smooth, emphasis on 'could'. Stop trying so hard and maybe something good will come from it."]
healthlist9 = []
familylist9 = ["Take some time away from family this week - they are sick of you.", "A distant member of your family will turn up to insult you.", "You will have a gut feeling that your family went on holiday without you - they did."]
worklist9 = []
financelist9 = []
travellist9 = ["A seagull will steal your doughnut and flap its wings into your face.", "Allowing other people to plan your trip doesn't always work in your favour.", "Your new passport will only arrive the day you are planning to leave for your holiday."]

lovelist10 = ["Love can be beautiful, but you'll be lucky if it has a great personality and laughs at your jokes.", "Sleep on the couch tonight. You'll thank me later.", "You thought you could do better than them. You were wrong and now you have no hope."]
healthlist10 = []
familylist10 = ["Your family have joined a cult - they will try to indoctrinate you.", "A distant member of your family will contact you about you car's extended warranty.", "You may find yourself cleaning crayon off the walls wondering where you went wrong."]
worklist10 = []
financelist10 = []
travellist10 = ["Suncream will leak into you suitcase - this is unfortunate for many reasons. Firstly, sun cream is very expensive and secondly, your clothes will be covered in it.", "There is part of me that doesn't want to tell you this but you won't find the love of your life on a beach in spain.", "If you order lamb in the mediterranean, it will most likely be goat."] 

lovelist11 = ["Sometimes you just have to know when to give up.", "Maybe pick a different aspect... I don't think you'll like this one.", "AHAHAHAHAHA ah thank you, I needed a good laugh."]
healthlist11 = []
familylist11 = ["A distant member of your family has found your secret stash.", "You may find yourself alone at the dinner table, wondering where you went wrong.", "If you're going on a family holiday this summer, prepare for some drama."]
worklist11 = []
financelist11 = []
travellist11 = ["Your plane will be delayed because you packed the wrong size bag.", "Seasickness will ruin any future sailing experiences.", "Your inability to learn the language of the country you are visiting will come back to bite you."] 


